question_data = {"response_code": 0,
                 "results": [
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Cartoon &amp; Animations",
                      "question": "In the &quot;Shrek&quot; film franchise, Donkey is played by Eddie Murphy.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]
                      },
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                      "question": "Daft Punk originated in France.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
                      "question": "In Chobits, Hideki found Chii in his apartment.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                      "question": "Faust is a playable character in &quot;Guilty Gear Xrd Revelator&quot;.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "You can legally drink alcohol while driving in Mississippi.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                      "question": "Nintendo&#039;s Luigi was originally just called Green Mario?",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                      "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "History",
                      "question": "Vikings were the first Europeans to discover North America.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Geography",
                      "question": "A group of islands is called an &#039;archipelago&#039;.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                      "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                      "question": "The Kerbol System (from Kerbal Space Program) includes a Saturn analogue.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                      "question": "In the Monster Hunter Series, it is possible to capture Elder Dragons.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
                      "question": "In &quot;Star Trek&quot;, Klingons are aliens.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "When you cry in space, your tears stick to your face.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                      "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named &quot;Timmy&quot; and &quot;Jimmy&quot;.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "The Great Wall of China is visible from the moon.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "History",
                      "question": "Thomas Crapper was a plumber who invented the flushing toilet.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Animals",
                      "question": "A flock of crows is known as a homicide.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Gadgets",
                      "question": "Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                      "question": "A Saxophone is a brass instrument.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Animals",
                      "question": "Rabbits can&#039;t vomit.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                      "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Mathematics",
                      "question": "The sum of any two odd integers is odd.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Cartoon &amp; Animations",
                      "question": "Bill Cipher in the show &quot;Gravity Falls&quot; is the good guy.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                      "question": "The Mann Co. Store from Team Fortress 2 has the slogan &quot;We hire mercenaries and get in fights&quot;.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
                      "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990. ",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                      "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Animals",
                      "question": "A bear does NOT defecate during hibernation. ",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
                      "question": "In the &quot;Melancholy of Haruhi Suzumiya&quot; series, the narrator goes by the nickname Kyon.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                      "question": "In the Monster Hunter Series, G-Rank is the highest possible prestige a Hunter can recieve.",
                      "correct_answer": "True", "incorrect_answers": ["False"]}]}
